[package]
name = "stellar-event-assertion"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

# This crate is only used for testing, and not compatible with `wasm32` targets.
[target.'cfg(not(target_family = "wasm"))'.dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
stellar-tokens = { workspace = true }
