ignore:
  - "packages/macros/*"
  - "packages/**/test/*"
  - "packages/tokens/src/fungible/impl_token_interface_macro.rs"
  - "packages/tokens/src/fungible/overrides.rs"
  - "packages/tokens/src/non-fungible/overrides.rs"
