ignore:
  - "packages/contract-utils/access-control-macros"
  - "packages/contract-utils/ownable-macro"
  - "packages/contract-utils/macro-helpers"
  - "packages/tokens/fungible/src/impl_token_interface_macro.rs"
  - "packages/tokens/fungible/src/overrides.rs"
  - "packages/tokens/non-fungible/src/overrides.rs"
