ignore:
  - "packages/proc-macros/*"
  - "packages/tokens/src/fungible/impl_token_interface_macro.rs"
  - "packages/tokens/src/fungible/overrides.rs"
  - "packages/tokens/src/non-fungible/overrides.rs"
