[package]
name = "stellar-diamond-proxy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk = { workspace = true }
stellar-diamond-proxy-core = { workspace = true }
log = "0.4.20"
soroban-env-common = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[build-dependencies]
stellar-build-utils = { workspace = true }