[package]
name = "stellar-default-impl-macro-test"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

# This crate is only used for testing, and not compatible with `wasm32` targets.
[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
stellar-access = { workspace = true }
stellar-macros = { workspace = true }
stellar-event-assertion = { workspace = true }
stellar-tokens = { workspace = true }
