name: 🐞 Bug report
description: Create a report to help us improve
title: "🐞 [Bug]: "
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Briefly describe the issue you're experiencing. Tell us what you were trying to do and what happened instead. Remember, this is not a place to ask for help debugging code. For that, we welcome you in the OpenZeppelin Community Forum: https://forum.openzeppelin.com/.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: if you want, you can include screenshots as well
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
