[package]
name = "stellar-default-impl-macro-test"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

[lib]
crate-type = ["lib", "cdylib"]
doctest = false


[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
stellar-event-assertion = { workspace = true }
stellar-default-impl-macro = { workspace = true }
stellar-fungible = { workspace = true }
stellar-non-fungible = { workspace = true }
