[package]
name = "stellar-default-impl-macro-test"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

[lib]
crate-type = ["lib", "cdylib"]
doctest = false


[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
stellar-access-control = { workspace = true }
stellar-proc-macros = { workspace = true }
stellar-event-assertion = { workspace = true }
stellar-tokens = { workspace = true }
stellar-ownable = { workspace = true }
