[package]
name = "stellar-proc-macros"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
publish = false
description = "Proc macros for Stellar contracts."


[lib]
proc-macro = true
doctest = false

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
